Consider 2 vectors c(9,10,11,12) and c(13,14,15,16). Create a 4 by 2 matrix from these two vectors

In [15]:
a <- c(9,10,11,12)
b <- c(13,14,15,16)
MatrixA  <- matrix(c(a,b),nrow=4,ncol=2)
MatrixA

[,1] [,2]
[1,]  9   13  
[2,] 10   14  
[3,] 11   15  
[4,] 12   16

Add another vector c(17,18,19,20)as a column to the previous matrix.

In [20]:
c <- c(17,18,19,20)  # new vector
matrixA  <- matrix(c(a,b,c),nrow=4,ncol=3)  # increse the size of col to 3 
matrixA

[,1] [,2] [,3]
[1,]  9   13   17  
[2,] 10   14   18  
[3,] 11   15   19  
[4,] 12   16   20

In [26]:
# Using cbind method
matrixB <- matrix(c(a,b),nrow=4,ncol=2)

matrixB <- cbind(matrixB,c(17,18,19,20))
matrixB

[,1] [,2] [,3]
[1,]  9   13   17  
[2,] 10   14   18  
[3,] 11   15   19  
[4,] 12   16   20

 Assignment - 2 :
 Using built-in dataset iris, implement all the functions we have learnt in this tutorial